### ISSUE TITLE
Unable to add spawns (Fixed, plugin got an update)

### ISSUE THREAD

**Issue by ThomasAdnum** [B3none/cs2-retakes#119]
As you can see from the screenshot below, the command '!addspawn' works, and gives the required response. 

But when I use it as normal '!addspawn t/ct' nothing happens. This never happened before the 27th April (roughly on that day), and it was working perfectly before this. I didn't change anything on the server or add anything to the config so im completely lost. 

(also idk why the net graph is saying April 26th, I took this today ahhahah)

![20240429120656_1](https://github.com/B3none/cs2-retakes/assets/31847081/a1aad868-d5dc-4adf-9925-b0bb9c6eb935)

**Comment by B3none** [comment]
```
21:31:16  EROR (cssharp:Core) Error invoking callback
Apr 26 21:31:16:  System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
Apr 26 21:31:16:  ---> System.MissingMethodException: Method not found: 'Boolean ByRef CounterStrikeSharp.API.Core.CCSPlayerPawnBase.get_InBombZoneTrigger()'.
Apr 26 21:31:16:  at RetakesPlugin.RetakesPlugin.OnCommandAddSpawn(CCSPlayerController player, CommandInfo commandInfo)
Apr 26 21:31:16:  at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 159
Apr 26 21:31:16: at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
Apr 26 21:31:16:  at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
Apr 26 21:31:16:   --- End of inner exception stack trace ---
Apr 26 21:31:16:  at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
Apr 26 21:31:16: at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Apr 26 21:31:16:  at System.Delegate.DynamicInvokeImpl(Object[] args)
Apr 26 21:31:16:  at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```
this was the error a discord user was experiencing on 2.0.2

**Comment by ThomasAdnum** [comment]
Thanks for your quick response mate, the new update you launched fixed it :)
